Repository box/box-ui-elements, pull requests merged in 2025-09, with the labels that each got.

#4260 fix(metadata-view): Hide keyword and location filters
  package.json
  src/elements/common/sub-header/__tests__/SubHeaderRight.test.tsx
  src/elements/content-explorer/MetadataViewContainer.tsx
  src/elements/content-explorer/__tests__/ContentExplorer.test.tsx
  src/elements/content-explorer/__tests__/MetadataViewContainer.test.tsx
  yarn.lock
Labels: ready-to-merge

#4268 fix(content-explorer): Validate selected item ids after item changes
  src/elements/content-explorer/ContentExplorer.tsx
Labels: ready-to-merge

#4265 fix(metadata-view): Enable sorting dropdown
  src/elements/content-explorer/ContentExplorer.tsx
  src/elements/content-explorer/MetadataViewContainer.tsx
  src/elements/content-explorer/__tests__/ContentExplorer.test.tsx
  src/elements/content-explorer/__tests__/MetadataViewContainer.test.tsx
Labels: ready-to-merge

#4262 fix(metadata-view): default iconcolumnvariant
  src/elements/content-explorer/MetadataViewContainer.tsx
Labels: ready-to-merge

#4273 fix(metadataeditor): portal dropdown to preview container
  src/elements/content-preview/ContentPreview.js
  src/elements/content-preview/PreviewContext.ts
  src/elements/content-preview/stories/tests/ContentPreview-metadata-visual.stories.js
  src/elements/content-sidebar/MetadataInstanceEditor.tsx
Labels: ready-to-merge

#4275 feat(timestamped-comments): enable timestamp handling in sidebar
  i18n/en-US.properties
  src/components/form-elements/draft-js-mention-selector/DraftJSMentionSelector.js
  src/components/form-elements/draft-js-mention-selector/DraftTimestamp.scss
  src/components/form-elements/draft-js-mention-selector/README.md
  src/components/form-elements/draft-js-mention-selector/__tests__/DraftJSMentionSelector.test.js
  src/components/form-elements/draft-js-mention-selector/__tests__/createMentionSelectorState.test.js
  src/components/form-elements/draft-js-mention-selector/__tests__/createMentionTimestampSelectorState.test.js
  src/components/form-elements/draft-js-mention-selector/__tests__/utils.test.js
  src/components/form-elements/draft-js-mention-selector/createMentionSelectorState.js
  src/components/form-elements/draft-js-mention-selector/createMentionTimestampSelectorState.js
  src/components/form-elements/draft-js-mention-selector/index.js
  src/components/form-elements/draft-js-mention-selector/utils.js
  src/elements/content-sidebar/activity-feed/activity-feed/ActiveState.js
  src/elements/content-sidebar/activity-feed/comment-form/CommentForm.js
  src/elements/content-sidebar/activity-feed/comment/__tests__/Comment.test.js
  src/elements/content-sidebar/activity-feed/common/activity-message/ActivityMessage.js.flow
  src/elements/content-sidebar/activity-feed/common/activity-message/ActivityMessage.scss
  src/elements/content-sidebar/activity-feed/common/activity-message/ActivityMessage.tsx
  src/elements/content-sidebar/activity-feed/common/activity-message/messages.js
  src/elements/content-sidebar/activity-feed/utils/__tests__/formatTaggedMessage.test.js
  src/elements/content-sidebar/activity-feed/utils/formatTaggedMessage.js
  src/utils/__tests__/timestamp.test.js
  src/utils/timestamp.js.flow
  src/utils/timestamp.ts
Labels: ready-to-merge

#4281 chore: add usm packages
  package.json
  scripts/i18n.config.js
  yarn.lock
Labels: ready-to-merge

#4279 feat(classification): AppliedByAiClassificationReason card to support empty reason
  src/features/classification/Classification.scss
  src/features/classification/applied-by-ai-classification-reason/AppliedByAiClassificationReason.scss
  src/features/classification/applied-by-ai-classification-reason/AppliedByAiClassificationReason.tsx
  src/features/classification/applied-by-ai-classification-reason/__tests__/AppliedByAiClassificationReason.test.tsx
  src/features/classification/flowTypes.js
  src/features/classification/types.ts
Labels: ready-to-merge

#4282 feat(content-sharing): Create ContentSharingV2 component
  scripts/jest/jest.config.js
  src/elements/content-sharing/ContentSharing.js
  src/elements/content-sharing/ContentSharingV2.tsx
  src/elements/content-sharing/stories/ContentSharing.stories.js
  src/elements/content-sharing/stories/ContentSharingV2.stories.tsx
  src/elements/content-sharing/stories/tests/ContentSharingV2-visual.stories.tsx
Labels: ready-to-merge

#4276 fix(common): Remove findDOMNode from makeDroppable (BREAKING CHANGE)
  src/elements/common/droppable/__tests__/makeDroppable.test.js
  src/elements/common/droppable/__tests__/makeDroppable.test.tsx
  src/elements/common/droppable/makeDroppable.js
  src/elements/content-uploader/DroppableContent.tsx
Labels: ready-to-merge

#4280 fix(i18n): update translations
  i18n/bn-IN.properties
  i18n/da-DK.properties
  i18n/de-DE.properties
  i18n/en-AU.properties
  i18n/en-CA.properties
  i18n/en-GB.properties
  i18n/es-419.properties
  i18n/es-ES.properties
  i18n/fi-FI.properties
  i18n/fr-CA.properties
  i18n/fr-FR.properties
  i18n/hi-IN.properties
  i18n/it-IT.properties
  i18n/ja-JP.properties
  i18n/ko-KR.properties
  i18n/nb-NO.properties
  i18n/nl-NL.properties
  i18n/pl-PL.properties
  i18n/pt-BR.properties
  i18n/ru-RU.properties
  i18n/sv-SE.properties
  i18n/tr-TR.properties
  i18n/zh-CN.properties
  i18n/zh-TW.properties
Labels: queued

#4270 fix(metadata-view): show error state when exception is thrown
  src/elements/content-explorer/Content.tsx
  src/elements/content-explorer/MetadataViewContainer.tsx
  src/elements/content-explorer/__tests__/Content.test.tsx
Labels: ready-to-merge

#4239 feat(content-sidebar): implement for custom sidebar panels
  src/elements/content-sidebar/ContentSidebar.js
  src/elements/content-sidebar/Sidebar.js
  src/elements/content-sidebar/SidebarNav.js
  src/elements/content-sidebar/SidebarPanels.js
  src/elements/content-sidebar/__tests__/SidebarNav.test.js
  src/elements/content-sidebar/__tests__/SidebarPanels.test.js
  src/elements/content-sidebar/flowTypes.js
  src/elements/content-sidebar/stories/BoxAISideBar.mdx
  src/elements/content-sidebar/stories/BoxAISidebar.stories.tsx
  src/elements/content-sidebar/stories/tests/BoxAISidebar-visual.stories.tsx
  src/elements/content-sidebar/stories/tests/ContentSidebar-visual.stories.tsx
Labels: ready-to-merge, queued

#4285 feat(content-sharing): Convert Content Sharing V2 API Response
  package.json
  src/elements/content-sharing/ContentSharing.js
  src/elements/content-sharing/ContentSharingV2.tsx
  src/elements/content-sharing/__tests__/ContentSharingV2.test.tsx
  src/elements/content-sharing/stories/ContentSharingV2.stories.tsx
  src/elements/content-sharing/stories/tests/ContentSharingV2-visual.stories.tsx
  src/elements/content-sharing/types.js
  src/elements/content-sharing/utils/__mocks__/ContentSharingV2Mocks.js
  src/elements/content-sharing/utils/__tests__/convertItemResponse.test.ts
  src/elements/content-sharing/utils/__tests__/getAllowedAccessLevels.test.ts
  src/elements/content-sharing/utils/__tests__/getAllowedPermissionLevels.test.ts
  src/elements/content-sharing/utils/constants.ts
  src/elements/content-sharing/utils/convertItemResponse.ts
  src/elements/content-sharing/utils/getAllowedAccessLevels.ts
  src/elements/content-sharing/utils/getAllowedPermissionLevels.ts
  src/elements/content-sharing/utils/index.ts
  yarn.lock
Labels: ready-to-merge, queued

#4286 fix(security-cloud-game): Use nodeRef in DragCloud for React 19
  package.json
  src/features/security-cloud-game/DragCloud.js
  yarn.lock
Labels: ready-to-merge, queued

#4318 feat(video-annotations): sidebar support for video annotations
  src/elements/content-sidebar/activity-feed/annotations/AnnotationActivity.js
  src/elements/content-sidebar/activity-feed/annotations/__tests__/AnnotationActivity.test.js
  src/elements/content-sidebar/activity-feed/common/activity-message/ActivityMessage.tsx
  src/elements/content-sidebar/activity-feed/common/activity-message/__tests__/ActivityMessage.test.js
  src/elements/content-sidebar/activity-feed/utils/formatTaggedMessage.js
Labels: ready-to-merge, queued
